

{{- $templateValues := fromYaml (include "hlmfk-0-0-5d80547625.valuesYaml" (dict "Values" .Values)) }}
{{- $values := merge $templateValues (pick .Values "overlay") }}

{{- $all := fromYaml (include "hlmfk-0-0-5d80547625.yamls" (dict "Values" $values) ) }}


{{- if $values.manifests }}
{{- range $key, $manifest := $values.manifests }}
{{- $result := append $all.manifests (dict "spec" $manifest) }}
{{- $n := set $all "manifests" $result -}}
{{- end }}
{{- end }}

{{- range $key, $manifest := $all.manifests }}
{{- $globals := "" }}
{{- if $values.helmifyPrefix }}
  {{- $globals = index $values $values.helmifyPrefix }}
{{- else }}
  {{- $globals = $values.globals }}
{{- end }}
{{- include "hlmfk-0-0.ensureMetadata" (dict "manifest" $manifest)}}
{{- include "hlmfk-0-0.updataImages" (dict "manifest" $manifest "globals" $globals)}}
{{- if $globals }}
{{- include "hlmfk-0-0.setNamespace" (dict "manifest" $manifest "globals" $globals)}}
{{- include "hlmfk-0-0.setNamePrefix" (dict "manifest" $manifest "globals" $globals)}}
{{- include "hlmfk-0-0.setNameSuffix" (dict "manifest" $manifest "globals" $globals)}}
{{- include "hlmfk-0-0.nameReleasePrefix" (dict "manifest" $manifest "globals" $globals "Values" $values)}}
{{- include "hlmfk-0-0.labels" (dict "manifest" $manifest "globals" $globals)}}
{{- include "hlmfk-0-0.annotations" (dict "manifest" $manifest "globals" $globals)}}
{{- include "hlmfk-0-0.applyManifestPatchers" (dict "manifest" $manifest "globals" $globals)}}
{{- end}}


{{- if and (hasKey $.Values "env") }}
{{ include "hlmfk-0-0.updateConfigMap" (dict "manifest" $manifest "name" "mcp-s-grafana-container-vars" "data" $.Values.env) }}
{{- end }}

{{- end }}



{{- if .Values.resources }}
{{- range $key, $manifest := .Values.resources }}
{{- $result := append $all.manifests (dict "spec" $manifest) }}
{{- $n := set $all "manifests" $result -}}
{{- end }}
{{- end }}

{{- include "hlmfk-0-0.printManifests" $all }}
        